version: 1.0.{build}

environment:
  GCCGenerator: "MinGW Makefiles"
  matrix:
    - generator: "Visual Studio 12"
    - generator: "Visual Studio 13"
    - generator: "Visual Studio 14"

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init
  - cmd: choco install cmake 
  - cmd: if "%generator%" == "%GCCGenerator%" choco install mingw > nul # The mingw installer is in verbose mode, see https://chocolatey.org/packages/mingw
  - cmd: cmake --version
  - cmd: if "%generator%" == "%GCCGenerator%" g++ --version

build_script:
  - cmd: IF NOT EXIST build mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%generator%" -DCMAKE_BUILD_TYPE="%configuration%"
  - cmd: cmake --build . --config "%configuration%"

test_script:
  - cmd: ctest -C "%configuration%" . -VV


